package MENTORING._08_Try_Catch;

public class _04_Soru {

    public static void main(String[] args) {
/*     TODO --> hiyerarji en başta Exeption ile başladığı için alttaki hatalar gereksiz hata veriyor.
        try{
            int arr[]=new int[7];
            arr[10]=10/5;
            System.out.HuseyinBYCalısma.println("Last Statement of try block");
        }
        catch(Exception e){
            System.out.HuseyinBYCalısma.println("Some Other Exception");
        }
       catch(ArithmeticException e){
            System.out.HuseyinBYCalısma.println("You should not divide a number by zero");
        }
        catch(ArrayIndexOutOfBoundsException e){
            System.out.HuseyinBYCalısma.println("Accessing array elements outside of the limit");
        }
        System.out.HuseyinBYCalısma.println("Out of the try-catch block");

 */
    }
}